version: '3.3'

services:
  minio:
    container_name: minio
    hostname: minio-test
    network_mode: host
    image: quay.io/minio/minio
    restart: always
    command:
      - server
      - /data
      - "--console-address"
      - ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 30s
      timeout: 10s
      retries: 5
  prepare_buckets:
    container_name: minio-setup
    image: quay.io/minio/minio
    network_mode: host
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        mc alias set e2e "http://localhost:9000" minioadmin minioadmin
        mc admin info e2e
        mc mb e2e/tmp && mc mb e2e/lakehouse
  trino:
    depends_on:
      lakekeeper:
        condition: service_healthy
    network_mode: host
    image: "trinodb/trino:474"
    volumes:
      - ./integration-tests.properties:/etc/trino/catalog/iceberg.properties
##  http-proxy:
##    image: "envoyproxy/envoy:v1.31.2"
##    command:
##      - envoy
##      - "-c"
##      - /etc/envoy/envoy.yaml
##    volumes:
##      - ./http-proxy-envoy-config.yaml:/etc/envoy/envoy.yaml
  lakekeeper:
    image: quay.io/lakekeeper/catalog:v0.9.2
    network_mode: host
    environment:
#      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__LISTEN_PORT=20001
      - LAKEKEEPER__METRICS_PORT=20002
      - LAKEKEEPER__BASE_URI=http://localhost:20001
      - ICEBERG_REST__BASE_URI=http://localhost:20001
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@localhost:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@localhost:5432/postgres
      - RUST_LOG=trace,axum=trace,sqlx=trace,iceberg-catalog=trace
    command: [ "serve" ]
    healthcheck:
      test: [ "CMD", "/home/nonroot/lakekeeper", "healthcheck" ]
      interval: 1s
      timeout: 10s
      retries: 30
    depends_on:
      lakekeeper_migrate:
        condition: service_completed_successfully
      lakekeeper_db:
        condition: service_healthy
      minio:
        condition: service_healthy
  lakekeeper_migrate:
    image: quay.io/lakekeeper/catalog:v0.9.2
    network_mode: host
    environment:
#      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@localhost:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@localhost:5432/postgres
      - RUST_LOG=info
    restart: "no"
    command: [ "migrate" ]
    depends_on:
      lakekeeper_db:
        condition: service_healthy
  lakekeeper_prepare:
    image: python:3.11-slim-bookworm
    network_mode: host
    environment:
      CATALOG_HOST: localhost
      CATALOG_WAREHOUSE: demo
    depends_on:
      lakekeeper:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./bootstrap-lk.py:/bootstrap-lk.py
    command: [ "/bin/sh", "-c", "pip install requests && python /bootstrap-lk.py"  ]
  lakekeeper_db:
    image: postgres:16.3-bullseye
    network_mode: host
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - PGHOST=localhost
      - PGPORT=5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres" ]
      interval: 2s
      timeout: 30s
      retries: 8

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "tMIxN11yGZgMC"
    container_name: sql-server
    hostname: sql-server
    restart: always
    ports:
      - "1433:1433"

  setup_mssql:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    restart: "no"
    volumes:
      - ./:/app
    entrypoint:
      - "bash"
      - "-c"
      - |
        while ! /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P tMIxN11yGZgMC -Q "SELECT 1"; do
          sleep 1
        done
        /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P tMIxN11yGZgMC -i /app/integration-tests.sql
